apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cleanup-cronjob
  labels:
    app: {{ .Values.otcExtension.name }}
    job: {{ .Release.Name }}-cleanup-cronjob
spec:
  schedule: {{.Values.schedule | quote}}
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  jobTemplate:
    metadata:
      name: {{ .Release.Name }}-cleanup-cronjob
      labels:
        job: {{ .Release.Name }}-cleanup-cronjob
        app: {{ .Release.Name }}-cleanup
    spec:
      activeDeadlineSeconds: {{ .Values.activeDeadlineSeconds | default 2700  }}
      backoffLimit: 1
      template:
        metadata:
          name: {{ .Release.Name }}-cleanup
          labels:
            app: {{ .Release.Name }}-cleanup
            job: {{ .Release.Name }}-pod-cleanup-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: {{  .Release.Name }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
              env:
                {{- range $key, $val := .Values.otcExtension.env }}
                - name: {{ $key }}
                  value: {{ $val | quote }}
                {{- end }}
              args: [ "/bin/bash", "/opt/cleanup-manual-backups.sh" ]
              volumeMounts:
                - name: {{.Release.Name}}-script
                  mountPath: "/opt/"
          volumes:
            - name: {{.Release.Name}}-script
              configMap:
                name: rds-backup-scripts
                defaultMode: 0777
