apiVersion: v1
kind: ConfigMap
metadata:
  name: automated-manual-rds-backup-script
data:
  create-manual-backup.sh: |
    #!/bin/bash
    timestamp=$(date +%F)
    function createBackup()
    {
      echo "Starting to create a auto manual backup of rds {{ .Values.otcrds.name }}"
      rds_backup_id=$(openstack rds backup create --description "backup from {{ .Values.otcrds.name }}-$timestamp" "{{ .Release.Name }}-{{ .Values.otcrds.name }}-$timestamp" {{ .Values.otcrds.id }} | jq '.id' )
      error=$?
      if [ $error -ne 0 ]; then
          exit 1
      fi
      size=$(openstack rds backup list --backup-id $rds_backup_id {{ .Values.otcrds.id }} -f json | jq '.[] | ."Size (KB)"')
      error=$?
      if [ $error -ne 0 ]; then
        exit 1
      fi
      while [[ $size -gt 0 ]]
      do
        echo -n "Creating Backup {{ .Values.otcrds.name }}-$timestamp in progress..."
        size=$(openstack rds backup list --backup-id $rds_backup_id {{ .Values.otcrds.id }} -f json | jq '.[] | ."Size (KB)"')
        error=$?
        if [ $error -ne 0 ]; then
          exit 1
        fi
        sleep 30
        echo -n -e "\e[0K\r"
      done
      echo -e "Finished with manual rds backup of db: {{ .Values.otcrds.name }}"
    }
    createBackup