apiVersion: v1
kind: ConfigMap
metadata:
  name: automated-manual-rds-backup-script
data:
  create-manual-backup.sh: |
    #!/bin/bash
    timestamp=$(date +%F)
    function createBackup()
    {
      echo "Starting to create a auto manual backup of rds {{ .Values.otcRDS.name }}"
      rds_backup_id=$(openstack rds backup create --description "backup from {{ .Values.otcRDS.name }}-$timestamp" "{{ .Release.Name }}-{{ .Values.otcRDS.name }}-$timestamp" {{ .Values.otcRDS.id }} -f json | jq --raw-output '.id' )
      if [ -z $rds_backup_id ]; then
          exit 1
      fi
      size=$(openstack rds backup list --backup-id $rds_backup_id {{ .Values.otcRDS.id }} -f json | jq --raw-output '.[] | ."Size (KB)"')
      if [ -z $size ]; then
        exit 1
      fi
      while [[ $size -eq 0 ]]
      do
        echo -n "Creating Backup {{ .Values.otcRDS.name }}-$timestamp in progress..."
        size=""
        size=$(openstack rds backup list --backup-id $rds_backup_id {{ .Values.otcRDS.id }} -f json | jq --raw-output '.[] | ."Size (KB)"')
        if [ -z $size ]; then
          exit 1
        fi
        sleep 15
        echo -n -e "\e[0K\r"
      done
      echo -e "Finished with manual rds backup of db: {{ .Values.otcRDS.name }}"
    }
    createBackup