# This will schedule at 05:00 CEST everyday
schedule: "0 3 * * *"
# one hour timeout
activeDeadlineSeconds: 1000
# Number of most recent backups to keep (one backup per day is created); 3 is example/default number of days
keepDays: 3
image:
  repository: iits/python-otcextension
  tag: 0.26.0
  pullPolicy: IfNotPresent
otcRDS:
  # Name of the database which of you want manual backups
  name:
otcExtension:
  env:
    # Theses are the necessary settings for authentication on OTC
    OS_USERNAME: "USERNAME"
    OS_PASSWORD: "PASSWORD"
    OS_PROJECT_NAME: eu-de
    OS_USER_DOMAIN_NAME: OTC-EU-DE-0000000000X0000XXXXX
    OS_AUTH_URL: https://iam.eu-de.otc.t-systems.com:443/v3
    # Don't change the following without considering the otc doc!
    OS_IMAGE_API_VERSION: 2
    OS_IDENTITY_API_VERSION: 3
    OS_VOLUME_API_VERSION: 3
    OS_ENDPOINT_TYPE: publicURL
    CINDER_ENDPOINT_TYPE: publicURL
    NOVA_ENDPOINT_TYPE: publicURL
